name = "ZZZTools"
uuid = "84f9d8bd-4fea-4352-8688-0db58772411f"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[deps]
JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"

[compat]
JSON2 = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]
